name: learning-workflow
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
    - main
  schedule:
    - cron: '30 5,17 * * *'
    
jobs:
  we-are-on-board:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: module3_task0

    steps:
      - run: make help
