name: module3_task0
run-name: module3_task0
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5,17 * * *'
defaults:
  run:
    shell: bash
    working-directory: module3_task0
jobs:
  we-are-on-board:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: make help
