name: module3_task1
run-name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5,17 * * *'
defaults:
  run:
    shell: bash
    working-directory: module3_task1
jobs:
  run-setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./setup.sh
      - run: build make
