name: module3_task3
run-name: module3_task3
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5,17 * * *'
defaults:
  run:
    shell: bash
    working-directory: module3_task3
jobs:
  run-setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./setup.sh
      - run: make build
      - if: success()
        run: make package
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.0')
